export const isprlDataPayload = {
  "metadata": {
    "datasetName": "ISPRL Strategic Petroleum Reserve Sovereign Dataset",
    "sourceFile": "data/EnergyShield_ISPRL_Reserve_Data.xlsx",
    "totalRecords": 34,
    "ingestedAt": "2026-08-23T04:08:32.337912",
    "validationStatus": "VALIDATED",
    "validationErrors": [],
    "reconciliation": {
      "status": "RECONCILED_BY_CLASSIFICATION",
      "title": "ISPRL Phase-I Storage Capacity Reconciliation by Classification",
      "totalPhysicalInstalledCapacityMmt": 5.33,
      "strategicStorageCapacityMmt": 5.03,
      "commercialLeasedCapacityMmt": 0.3,
      "isReconciled": true,
      "reconciliationFormula": "5.03 MMT (Strategic) + 0.3 MMT (HPCL Leased) = 5.33 MMT (Total Physical)",
      "vizagReconciliationFormula": "1.03 MMT (Cavern A Strategic) + 0.3 MMT (Cavern B Leased) = 1.33 MMT (Visakhapatnam Total)",
      "components": {
        "visakhapatnamTotalPhysicalMmt": 1.33,
        "visakhapatnamCavernA_StrategicMmt": 1.03,
        "visakhapatnamCavernB_HpclLeasedMmt": 0.3,
        "mangaloreStrategicMmt": 1.5,
        "padurStrategicMmt": 2.5
      },
      "explanation": "Capacity reconciles by classification: 5.33 MMT total physical capacity comprises 5.03 MMT strategic capacity plus 0.30 MMT HPCL-leased capacity at Visakhapatnam.",
      "policyDirective": "Preserve all source-reported values. Distinguish physical installed storage capacity (5.33 MMT) from sovereign strategic reserve capacity (5.03 MMT) and commercial leased capacity (0.30 MMT)."
    },
    "reconciliationFlags": [
      {
        "status": "RECONCILED_BY_CLASSIFICATION",
        "title": "ISPRL Phase-I Storage Capacity Reconciliation by Classification",
        "totalPhysicalInstalledCapacityMmt": 5.33,
        "strategicStorageCapacityMmt": 5.03,
        "commercialLeasedCapacityMmt": 0.3,
        "isReconciled": true,
        "reconciliationFormula": "5.03 MMT (Strategic) + 0.3 MMT (HPCL Leased) = 5.33 MMT (Total Physical)",
        "vizagReconciliationFormula": "1.03 MMT (Cavern A Strategic) + 0.3 MMT (Cavern B Leased) = 1.33 MMT (Visakhapatnam Total)",
        "components": {
          "visakhapatnamTotalPhysicalMmt": 1.33,
          "visakhapatnamCavernA_StrategicMmt": 1.03,
          "visakhapatnamCavernB_HpclLeasedMmt": 0.3,
          "mangaloreStrategicMmt": 1.5,
          "padurStrategicMmt": 2.5
        },
        "explanation": "Capacity reconciles by classification: 5.33 MMT total physical capacity comprises 5.03 MMT strategic capacity plus 0.30 MMT HPCL-leased capacity at Visakhapatnam.",
        "policyDirective": "Preserve all source-reported values. Distinguish physical installed storage capacity (5.33 MMT) from sovereign strategic reserve capacity (5.03 MMT) and commercial leased capacity (0.30 MMT)."
      }
    ]
  },
  "records": [
    {
      "id": "isprl-rec-01",
      "parameter": "Strategic storage capacity - total",
      "value": 5.03,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL About Us",
      "date": "2026-08-22",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL states that, after enhancement of Visakhapatnam capacity, strategic storage capacity was enhanced to 5.03 MMT.",
      "rowNumber": 3
    },
    {
      "id": "isprl-rec-02",
      "parameter": "Visakhapatnam strategic storage capacity",
      "value": 1.33,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL About Us",
      "date": "2026-08-22",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL states Visakhapatnam capacity as 1.33 MMT",
      "rowNumber": 4
    },
    {
      "id": "isprl-rec-03",
      "parameter": "Mangalore strategic storage capacity",
      "value": 1.5,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL About Us",
      "date": "2026-08-22",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL states Mangalore capacity as 1.50 MMT",
      "rowNumber": 5
    },
    {
      "id": "isprl-rec-04",
      "parameter": "Padur strategic storage capacity",
      "value": 2.5,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL About Us",
      "date": "2026-08-22",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL states Padur capacity as 2.50 MMT",
      "rowNumber": 6
    },
    {
      "id": "isprl-rec-05",
      "parameter": "Government of India crude oil inventory under custody",
      "value": 2921957.35,
      "unit": "MT",
      "category": "CRUDE_INVENTORY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL reports total Government of India crude oil under custody of 2,921,957.35 MT as at 31 March 2025",
      "rowNumber": 7
    },
    {
      "id": "isprl-rec-06",
      "parameter": "ADNOC crude oil under custody",
      "value": 421420.04,
      "unit": "MT",
      "category": "CRUDE_INVENTORY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL reports ADNOC crude oil under custody of 421,420.04 MT at 31 March 2025, excluding dead stock",
      "rowNumber": 8
    },
    {
      "id": "isprl-rec-07",
      "parameter": "Visakhapatnam HPCL leased cavern capacity",
      "value": 0.3,
      "unit": "MMT",
      "category": "COMMERCIAL_LEASE",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL states that 0.30 MMT capacity of Cavern A at Visakhapatnam is rented/leased to HPCL.",
      "rowNumber": 9
    },
    {
      "id": "isprl-rec-08",
      "parameter": "Mangalore MRPL leased cavern capacity",
      "value": 0.76,
      "unit": "MMT",
      "category": "COMMERCIAL_LEASE",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "LOA was placed on MRPL on 26-Nov-2024 and agreement signed on 06-Jan-2025 for renting/leasing 0.760 MMT capacity of Cavern B at Mangalore; utilization had not commenced pending approvals.",
      "rowNumber": 10
    },
    {
      "id": "isprl-rec-09",
      "parameter": "Commercial leasing/renting allowance",
      "value": 30,
      "unit": "% of overall storage capacity",
      "category": "POLICY_PROPORTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Cabinet approval allows leasing/renting up to 30% of overall storage capacity.",
      "rowNumber": 11
    },
    {
      "id": "isprl-rec-10",
      "parameter": "Sale/purchase allowance",
      "value": 20,
      "unit": "% of overall storage capacity",
      "category": "POLICY_PROPORTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Cabinet approval allows sale/purchase of up to 20% of overall storage capacity.",
      "rowNumber": 12
    },
    {
      "id": "isprl-rec-11",
      "parameter": "Strategic portion",
      "value": 50,
      "unit": "% of overall storage capacity",
      "category": "POLICY_PROPORTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Remaining 50% of overall storage capacity remains strategic.",
      "rowNumber": 13
    },
    {
      "id": "isprl-rec-12",
      "parameter": "Sovereign crude sold from 30% commercial capacity",
      "value": 1.298,
      "unit": "MMT",
      "category": "SOVEREIGN_TRANSACTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL reports 1.298 MMT sovereign crude sold up to 31 March 2025 from the 30% capacity; proceeds returned to GOI/MoPNG.",
      "rowNumber": 14
    },
    {
      "id": "isprl-rec-13",
      "parameter": "Sovereign crude sold during FY 2024-25",
      "value": 0,
      "unit": "MMT",
      "category": "SOVEREIGN_TRANSACTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "No sovereign crude oil was sold during the current year.",
      "rowNumber": 15
    },
    {
      "id": "isprl-rec-14",
      "parameter": "ADNOC crude stored in Mangalore SPR",
      "value": 5.8,
      "unit": "Million barrels",
      "category": "OPERATIONAL_METRIC",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ADNOC filled approximately 5.8 million barrels of crude in ISPRL's Mangalore cavern in 2018.",
      "rowNumber": 16
    },
    {
      "id": "isprl-rec-15",
      "parameter": "ADNOC commercial-use portion",
      "value": 50,
      "unit": "% of ADNOC stored crude",
      "category": "POLICY_PROPORTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Under the agreement, ADNOC can use 50% portion of the oil as commercial supply to customers in India.",
      "rowNumber": 17
    },
    {
      "id": "isprl-rec-16",
      "parameter": "ADNOC strategic portion",
      "value": 50,
      "unit": "% of ADNOC stored crude",
      "category": "POLICY_PROPORTION",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "The remaining 50% remains strategic storage and can be released on directions of the Government of India during emergencies.",
      "rowNumber": 18
    },
    {
      "id": "isprl-rec-17",
      "parameter": "Visakhapatnam Cavern A capacity",
      "value": 1.03,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Visakhapatnam facility has Cavern A of 1.03 MMT; it is for strategic crude oil.",
      "rowNumber": 19
    },
    {
      "id": "isprl-rec-18",
      "parameter": "Visakhapatnam Cavern B capacity",
      "value": 0.3,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Visakhapatnam facility has Cavern B of 0.30 MMT; HPCL has taken Cavern B on a proportionate cost-sharing basis.",
      "rowNumber": 20
    },
    {
      "id": "isprl-rec-19",
      "parameter": "Mangalore Cavern A capacity",
      "value": 0.75,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Mangalore facility has two caverns of 0.75 MMT capacity each; Cavern A was filled under the ADNOC agreement.",
      "rowNumber": 21
    },
    {
      "id": "isprl-rec-20",
      "parameter": "Mangalore Cavern B capacity",
      "value": 0.75,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Mangalore facility has two caverns of 0.75 MMT capacity each; Cavern B was commissioned in October 2016.",
      "rowNumber": 22
    },
    {
      "id": "isprl-rec-21",
      "parameter": "Padur - number of caverns",
      "value": 4,
      "unit": "Caverns",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Padur has a total storage capacity of 2.5 MMT distributed evenly across four caverns.",
      "rowNumber": 23
    },
    {
      "id": "isprl-rec-22",
      "parameter": "Padur - capacity per cavern",
      "value": 0.625,
      "unit": "MMT per cavern",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Padur's 2.5 MMT capacity is distributed evenly across four caverns of 0.625 MMT each.",
      "rowNumber": 24
    },
    {
      "id": "isprl-rec-23",
      "parameter": "HPCL leased capacity at Visakhapatnam",
      "value": 0.3,
      "unit": "MMT",
      "category": "COMMERCIAL_LEASE",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL entered into an agreement with HPCL for renting 300 TMT (2.17 million barrels) of cavern capacity at Visakhapatnam effective 19 January 2024.",
      "rowNumber": 25
    },
    {
      "id": "isprl-rec-24",
      "parameter": "HPCL leased capacity at Visakhapatnam",
      "value": 2.17,
      "unit": "Million barrels",
      "category": "COMMERCIAL_LEASE",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "The 300 TMT cavern capacity leased to HPCL corresponds to approximately 2.17 million barrels.",
      "rowNumber": 26
    },
    {
      "id": "isprl-rec-25",
      "parameter": "HPCL first crude consignment at Visakhapatnam",
      "value": "2024-01-19",
      "unit": "Date",
      "category": "COMMERCIAL_LEASE",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL received its first consignment of Basrah Medium Crude in the HPCL-leased cavern on 19 January 2024.",
      "rowNumber": 27
    },
    {
      "id": "isprl-rec-26",
      "parameter": "HPCL leased crude type",
      "value": "Basrah Medium",
      "unit": "Crude grade",
      "category": "COMMERCIAL_LEASE",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "The leased Visakhapatnam cavern is being used by HPCL for storage of Basrah Medium crude oil.",
      "rowNumber": 28
    },
    {
      "id": "isprl-rec-27",
      "parameter": "Padur Phase-II planned strategic storage",
      "value": 2.5,
      "unit": "MMT",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL's Padur Phase-II project is planned for development of 2.5 MMT strategic petroleum reserve capacity.",
      "rowNumber": 29
    },
    {
      "id": "isprl-rec-28",
      "parameter": "Chandikhol Phase-II planned strategic storage",
      "value": 4,
      "unit": "MMT",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "In-principle approval was given for setting up a 4.0 MMT SPR facility at Chandikhol/Jajpur, Odisha.",
      "rowNumber": 30
    },
    {
      "id": "isprl-rec-29",
      "parameter": "Mangalore additional cavern project - revised capacity",
      "value": 1.75,
      "unit": "MMT",
      "category": "PHYSICAL_CAPACITY",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "The feasibility study for additional caverns at Mangalore was under revision with a revised capacity of 1.75 MMT.",
      "rowNumber": 31
    },
    {
      "id": "isprl-rec-30",
      "parameter": "Bikaner salt cavern project - planned capacity",
      "value": 5.625,
      "unit": "MMT",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL was revising the DFR for salt cavern strategic reserves at Bikaner to an increased capacity of 5.625 MMT.",
      "rowNumber": 32
    },
    {
      "id": "isprl-rec-31",
      "parameter": "Mangalore Phase-I extension - land",
      "value": 154.9,
      "unit": "Acres",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "ISPRL signed an MoU with MSEZL for 154.90 acres of land at Mangalore for construction of SPR and associated facilities.",
      "rowNumber": 33
    },
    {
      "id": "isprl-rec-32",
      "parameter": "Mangalore Phase-I extension - project status",
      "value": "DFR submitted",
      "unit": "Status",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Final DFR and project cost estimate were submitted by EIL in January 2025 and put before the competent authority for approvals.",
      "rowNumber": 34
    },
    {
      "id": "isprl-rec-33",
      "parameter": "Padur Phase-II - target completion",
      "value": "2030-08-01",
      "unit": "Date",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "Padur Phase-II is planned for 2.5 MMT SPR capacity; the reported target completion date is August 2030.",
      "rowNumber": 35
    },
    {
      "id": "isprl-rec-34",
      "parameter": "Chandikhol SPR - approved investment",
      "value": 8743,
      "unit": "INR crore",
      "category": "EXPANSION_PROJECT",
      "source": "ISPRL Annual Report 2024-25",
      "date": "2025-03-31",
      "status": "OFFICIAL",
      "sourceNote": "In-principle approval was given for the Chandikhol/Jajpur SPR project with an investment of INR 8,743 crore.",
      "rowNumber": 36
    }
  ]
};
export default isprlDataPayload;
